# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueLogs',
            fields=[
                ('issueId', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.IntegerField(choices=[(1, 'Sage UK'), (2, 'Sage Global'), (3, 'Nespresso')])),
            ],
        ),
    ]
